"""Generate Config/Music.luau from live Creator Store metadata for a hand-picked list of asset ids."""
import json
import sys
import urllib.request

PICKS = [
    1844280695,  # Mozart - Eine Kleine Nachtmusik, Minuet
    1838138329,  # Handel - Watermusic Suite in F Major
    1838535838,  # Rossini - Barber of Seville Overture
    1836281637,  # Rossini - Italian in Algiers Overture
    1848069929,  # Haydn - Symphony No.94 Surprise, Menuetto
    1847087940,  # Dvorak - Slavonic Dance Op.72/15 in C major
    1847143264,  # Dvorak - Slavonic Dance Op.72/03 in F major
    1836281953,  # Grieg - Peer Gynt, Anitra's Dance
    1838599484,  # Offenbach - Can Can
    1836282370,  # Tchaikovsky - Swan Lake Waltz
    1837487818,  # Vivaldi - Concerto No.3 in F major
]

req = urllib.request.Request(
    "https://apis.roblox.com/toolbox-service/v1/items/details?assetIds=" + ",".join(map(str, PICKS)),
    headers={"User-Agent": "GameV1-asset-tool"},
)
rows = {d["asset"]["id"]: d for d in json.load(urllib.request.urlopen(req, timeout=25))["data"]}

tracks = []
for pid in PICKS:
    d = rows.get(pid)
    if d is None:
        sys.exit(f"asset {pid} was not returned by the API")
    a, c = d["asset"], d["creator"]
    ad = a.get("audioDetails", {})
    problems = []
    if a.get("typeId") != 3:
        problems.append("not audio")
    if not d["fiatProduct"]["isFree"]:
        problems.append("not free")
    if a.get("hasScripts"):
        problems.append("has scripts")
    if not a.get("isAssetHashApproved"):
        problems.append("not approved")
    if not c.get("isVerifiedCreator"):
        problems.append("creator not verified")
    if problems:
        sys.exit(f"asset {pid} rejected: {problems}")
    clean = lambda s: (s or "").replace('"', "'").replace("\\", "")
    tracks.append((pid, clean(a["name"]), clean(ad.get("artist")), a["duration"], c["name"]))

lines = [
    "--!strict",
    "-- Background music playlist: classical repertoire from the verified production-music partner account",
    "-- APMOfficial, listed free on the Creator Store. GENERATED by tools/asset-search (metadata re-checked when",
    "-- generated). Tracks are shuffled and crossfaded by AudioManager. Add/remove entries freely; keep",
    "-- docs/ASSET_REGISTRY.md in sync. Chosen from titles and metadata only: nobody has listened yet.",
    "export type Track = { Id: string, Name: string, Artist: string, Seconds: number }",
    "",
    "return {",
    "\tVolume = 0.32, -- per-track volume before the Music group volume",
    "\tCrossfadeSeconds = 3,",
    "\tTracks = {",
]
for pid, name, artist, secs, creator in tracks:
    lines.append(f'\t\t{{ Id = "rbxassetid://{pid}", Name = "{name}", Artist = "{artist}", Seconds = {secs} }},')
lines += ["\t} :: { Track },", "}", ""]
open("src/ReplicatedStorage/Shared/Config/Music.luau", "w", encoding="utf-8", newline="\n").write("\n".join(lines))
total = sum(t[3] for t in tracks)
print(f"wrote {len(tracks)} tracks, {total // 60} min {total % 60} s total")
for t in tracks:
    print(f"  {t[0]:>12} {t[3]:>4}s {t[1][:44]:<44} {t[2]} ({t[4]})")
